/* eslint-disable no-unused-vars */
import { SpaceType } from "@/components/user.portal/views/Spaces";
import { PlanType, UserRole } from "@/interfaces/modals";
import { AuthState } from "@/interfaces/redux";
import { createSlice } from "@reduxjs/toolkit";

const initialState: AuthState = {
    email: null,
    username: null,
    token: null, 
    isAuthenticated: false,
    OTPAttemptsRemaining: 3,
    currency: null,
    plan: null,
    role: null,
    spaces: []
};

// createSlice allows you to define the Redux state slice in a single function,
// including the initial state, reducers, and action creators, making it easier to manage state and actions.
// when you create a slice using the createSlice function, it generates two key things: actions and reducer.
const authSlice = createSlice({
    name: "auth", // The name of the slice
    initialState: initialState, // The initial state of the slice
    // reducer functions are accepting the previous state and the action and return the new state
    reducers: {
        loginSuccess(state, action: { "payload": { username: string, email: string, token: string, currency: string, plan: PlanType, role: UserRole, spaces: {id: string, name: string, type: SpaceType}[] } }) {
            console.log("login success: ", action.payload.token)
            state.username = action.payload.username;
            state.token = action.payload.token;
            state.email = action.payload.email;
            state.currency = action.payload.currency;
            state.plan = action.payload.plan
            state.isAuthenticated = true;
            state.role = action.payload.role
            state.spaces = action.payload.spaces
        },
        logout(state) {
            state.username = null;
            state.token = null;
            state.email = null;
            state.isAuthenticated = false;
            localStorage.removeItem("smart-wallet-user")
        },
        setToken(state, action) {
            state.token = action.payload.token;
        },
        setUsername(state, action) {
            state.username = action.payload.username
        },
        setEmail(state, action) {
            state.email = action.payload.email
        },
        setCurrency(state, action) {
            state.currency = action.payload.currency
        },
        setPlan(state, action) {
            state.plan = action.payload.plan
        },
        setSpaces(state, action) {
            state.spaces = action.payload.spaces
        },
        setIsAuthenticated(state, action) {
            state.isAuthenticated = action.payload.isAuthenticated
        },
        setOTPAttemptsRemaining(state, action) {
            state.OTPAttemptsRemaining = action.payload.OTPAttemptsRemaining
        }
    }
})

// Redux Toolkit will generate action creators for each reducer that you have defined in your slice.
// cartSlice.actions is an object that contains those action creators.
// Here, we extract these specific action creators from the actions object,
// and export them available for import in other files.
export const { loginSuccess, logout, setEmail, setUsername, setIsAuthenticated, setToken, setSpaces, setOTPAttemptsRemaining, setCurrency } = authSlice.actions;

// This line exports the reducer function generated by the createSlice function as the default export from the module.
export default authSlice.reducer;
