/* eslint-disable no-unused-vars */
import { SpaceType } from "@/components/user.portal/views/Spaces";
import { PlanType, UserRole } from "@/interfaces/modals";
import { TransactionState } from "../../interfaces/redux";
import { createSlice } from "@reduxjs/toolkit";

const initialState: TransactionState = {
    transactions: [],
    loading: false,
    page: 1,
    total: 0
};

// createSlice allows you to define the Redux state slice in a single function,
// including the initial state, reducers, and action creators, making it easier to manage state and actions.
// when you create a slice using the createSlice function, it generates two key things: actions and reducer.
const TransactionSlice = createSlice({
    name: "auth", // The name of the slice
    initialState: initialState, // The initial state of the slice
    // reducer functions are accepting the previous state and the action and return the new state
    reducers: {
        getSuccess(state, action: { "payload": {total: number, transactions: any[]}}) {
            console.log("login success: ", action.payload)
            state.loading = false
            state.total = action.payload.total
            state.transactions = action.payload.transactions
        },
        getFail(state, action: { "payload": {total: number, transactions: any[]}}) {
            console.log("login success: ", action.payload)
            state.loading = false
            state.total = action.payload.total
            state.transactions = action.payload.transactions
        },
        setLoading(state, action) {
            state.loading = action.payload.loading;
        },
        setPage(state, action) {
            state.page = action.payload.page;
        },
    }
})

// Redux Toolkit will generate action creators for each reducer that you have defined in your slice.
// cartSlice.actions is an object that contains those action creators.
// Here, we extract these specific action creators from the actions object,
// and export them available for import in other files.
export const { getSuccess, getFail, setLoading, setPage } = TransactionSlice.actions;

// This line exports the reducer function generated by the createSlice function as the default export from the module.
export default TransactionSlice.reducer;
